swagger: "2.0"

info:
  description: Share bike system
  version: 1.0
  title: Swagger LendBike

basePath: "/api/v1"

tags:
- name: user_token
  description: Get you access token to put on header as Authorization tag
- name: bike
- name: station
- name: bill
  description: Generate monthly invoice
- name: lend
  description: The action of share a bike

paths:
  /auth/token:
    post:
      tags:
      - user_token
      summary: Get you access token to put on header as Authorization tag
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Generate a Authorization token with seven days to expire
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
      responses:
        200:
          description: successful operation
          schema:
            properties:
              token:
                type: string
              user:
                properties:
                  id:
                    type: integer
                    format: int32
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /bills/{year}/{month}:
    get:
      tags:
      - bill
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
        parameters:
      - name: year
        in: path
        description: Reference year
        required: true
        type: integer
        format: int64
      - name: month
        in: path
        description: Reference month
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Bills'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /lends/get_bike:
    post:
      tags:
      - lend
      summary: Start the bike lend
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            bike_code:
              type: string
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Lend'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /lends/leave_bike:
    post:
      tags:
      - lend
      summary: Start the bike lend
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            station_code:
              type: string
            distance:
              type: integer
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Lend'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /bikes:
    get:
      tags:
      - bike
      summary: Bikes list
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: successful operation
          schema:
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Bike'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /bikes/{id}:
    get:
      tags:
      - bike
      summary: Bike by id
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      - name: id
        in: path
        description: Bike Id
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Bike'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /stations:
    get:
      tags:
      - station
      summary: Station list
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: successful operation
          schema:
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Station'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer
  /stations/{id}:
    get:
      tags:
      - station
      summary: Station by id
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - name: "Authorization"
        description: User token generated on auth/token
        in: "header"
        required: true
        type: "string"
      - name: id
        in: path
        description: Station Id
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Station'
        400:
          description: Invalid status value
          schema:
            properties:
              errors:
                type: array
                items:
                  properties:
                    message:
                      type: string
                    status:
                      type: integer

definitions:
  Lend:
    type: object
    properties:
      id:
        type: integer
        format: int32
      bike_id:
        type: integer
        format: int32
      user_id:
        type: integer
        format: int32
      start_at:
        type: string
        format: date-time
      end_at:
        type: string
        format: date-time
      current:
        type: boolean
        default: true
      station_id:
        type: integer
        format: int32
      distance:
        type: integer
        format: int32
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    xml:
      name: Order
  Bills:
    properties:
      total_value:
        type: integer
      user:
        type: string
      reference:
        type: string
      result:
        properties:
          bill:
            items:
              properties:
                bike:
                  type: string
                origin:
                  type: string
                destiny:
                  type: string
                distance:
                  type: integer
                start_at:
                  type: string
                  format: date-time
                end_at:
                  type: string
                  format: date-time
                value:
                  type: string
  Bike:
    properties:
      id:
        type: integer
      type:
        type: string
      attributes:
        properties:
          code:
            type: string
          maintenance:
            type: boolean
            default: false
          active:
            type: boolean
            default: true
          lendActive:
            type: boolean
            default: true
  Station:
    properties:
      id:
        type: integer
      type:
        type: string
      attributes:
        properties:
          code:
            type: string
          name:
            type: string
          address:
            type: string
          vacancies:
            type: integer
          active:
            type: boolean
            default: false
          occupied_vacancies:
            type: integer
          bikes:
            type: array
            items:
              type: string

schemes:
  - http
